http:
  port: 8080
admin:
  port: 9876
  host: demo-gateway-dev-ptmm.3.us-1.fl0.io
apiEndpoints:
  api:
    host: demo-gateway-dev-ptmm.3.us-1.fl0.io
    paths: '/ip'
  users:
    host: demo-gateway-dev-ptmm.3.us-1.fl0.io
    paths: '/api/users'
    methods: ["GET"]
  posts:
    host: demo-gateway-dev-ptmm.3.us-1.fl0.io
    paths: '/api/posts'
    methods: ["GET"]
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usersServer:
    url: 'https://jsonplaceholder.typicode.com/users'
  postsServer:
    url: 'https://jsonplaceholder.typicode.com/posts'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersServer 
              changeOrigin: true
  posts:
    apiEndpoints:
      - posts
    policies:
      - proxy:
          - action:
              serviceEndpoint: postsServer 
              changeOrigin: true
